//! Deterministic, validated ZIP codec for Tuckmark's directory-tree exports.

use std::{
    collections::{BTreeMap, BTreeSet},
    io::{Cursor, Read, Write},
};

use serde::{Deserialize, Serialize};
use serde_json::Value;
use thiserror::Error;
use tuckmark_contracts::{
    ContractError, DataDirectoryManifest, DevdDataArchive, InventoryAdjustment, InventoryMaterial,
    InventorySnapshot, RuntimeSnapshot, TemplateRecord, TemplateVersion, WorkingCopyRecord,
    canonical_json_bytes, normalize_legacy_value,
};
use zip::{CompressionMethod, ZipArchive, ZipWriter, write::SimpleFileOptions};

pub const DIRECTORY_TREE_ARCHIVE_SCHEMA: &str = "tuckmark.runtime-export-archive.v1";
pub const LEGACY_DATA_ARCHIVE_SCHEMA: &str = "tuckmark.data-archive.v1";

const ARCHIVE_METADATA_PATH: &str = "archive.json";
const MANIFEST_PATH: &str = "manifest.json";
const SETTINGS_PATH: &str = "settings/app-settings.json";
const MAX_ENTRY_COUNT: usize = 4_096;
const MAX_ENTRY_BYTES: u64 = 4 * 1024 * 1024;
const MAX_TOTAL_BYTES: u64 = 32 * 1024 * 1024;

#[derive(Debug, Error)]
pub enum ArchiveCodecError {
    #[error("ZIP archive error: {0}")]
    Zip(#[from] zip::result::ZipError),
    #[error("I/O error while processing ZIP archive: {0}")]
    Io(#[from] std::io::Error),
    #[error("archive JSON error: {0}")]
    Json(#[from] serde_json::Error),
    #[error("archive contract validation failed: {0}")]
    Contract(#[from] ContractError),
    #[error("unsafe archive entry path: {0}")]
    UnsafeEntryPath(String),
    #[error("archive contains a forbidden control entry: {0}")]
    ForbiddenControlEntry(String),
    #[error("archive contains a duplicate entry: {0}")]
    DuplicateEntry(String),
    #[error("archive directory entries are not permitted: {0}")]
    DirectoryEntry(String),
    #[error("archive entries must be JSON files: {0}")]
    NonJsonEntry(String),
    #[error("archive has too many entries: {0}")]
    TooManyEntries(usize),
    #[error("archive entry is too large: {path} ({size} bytes)")]
    EntryTooLarge { path: String, size: u64 },
    #[error("archive uncompressed payload is too large: {0} bytes")]
    TotalTooLarge(u64),
    #[error("archive is missing required {0}")]
    MissingRequiredEntry(String),
    #[error("unsupported archive metadata schema: {0}")]
    UnsupportedMetadataSchema(String),
    #[error("legacy tuckmark.data-archive.v1 requires decode_legacy_archive_metadata")]
    LegacySnapshotRequiresDirectDecode,
    #[error("invalid archive: {0}")]
    Invalid(String),
    #[error("manifest count mismatch for {kind}: expected {expected}, found {actual}")]
    ManifestCountMismatch {
        kind: &'static str,
        expected: u64,
        actual: u64,
    },
}

#[derive(Clone, Debug, PartialEq)]
pub struct DirectoryTreeArchive {
    pub exported_at: String,
    pub manifest: DataDirectoryManifest,
    /// JSON data files only. `archive.json` and `manifest.json` are generated by the codec.
    pub entries: BTreeMap<String, Value>,
}

#[derive(Clone, Debug, PartialEq)]
pub enum ArchiveZipInput {
    DirectoryTree(DirectoryTreeArchive),
    LegacySnapshot(DevdDataArchive),
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
struct ArchiveMetadata {
    schema: String,
    exported_at: String,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum EntryKind {
    Settings,
    Template,
    Version,
    WorkingCopy,
    Material,
    Adjustment,
}

impl DirectoryTreeArchive {
    pub fn new(
        exported_at: impl Into<String>,
        manifest: DataDirectoryManifest,
        entries: BTreeMap<String, Value>,
    ) -> Result<Self, ArchiveCodecError> {
        let archive = Self {
            exported_at: exported_at.into(),
            manifest,
            entries,
        };
        archive.validate()?;
        Ok(archive)
    }

    pub fn from_devd_data_archive(archive: &DevdDataArchive) -> Result<Self, ArchiveCodecError> {
        archive.validate()?;

        let mut entries = BTreeMap::new();
        insert_entry(
            &mut entries,
            SETTINGS_PATH.into(),
            archive.runtime.settings.clone(),
        )?;
        for template in &archive.runtime.templates {
            insert_entry(
                &mut entries,
                format!("templates/{}/template.json", safe_segment(&template.id)?),
                serde_json::to_value(template)?,
            )?;
        }
        for version in &archive.runtime.versions {
            insert_entry(
                &mut entries,
                format!(
                    "templates/{}/versions/{}.json",
                    safe_segment(&version.template_id)?,
                    safe_segment(&version.id)?,
                ),
                serde_json::to_value(version)?,
            )?;
        }
        for working_copy in &archive.runtime.working_copies {
            insert_entry(
                &mut entries,
                working_copy_path(working_copy)?,
                serde_json::to_value(working_copy)?,
            )?;
        }
        for material in &archive.inventory.materials {
            insert_entry(
                &mut entries,
                format!("inventory/materials/{}.json", safe_segment(&material.id)?),
                serde_json::to_value(material)?,
            )?;
        }
        for adjustment in &archive.inventory.adjustments {
            insert_entry(
                &mut entries,
                format!(
                    "inventory/adjustments/{}.json",
                    safe_segment(&adjustment.id)?,
                ),
                serde_json::to_value(adjustment)?,
            )?;
        }

        let mut manifest =
            DataDirectoryManifest::new("backup-archive", archive.exported_at.clone());
        manifest.snapshot_updated_at = archive.runtime.snapshot_updated_at.clone();
        manifest.counts.templates = archive.runtime.templates.len() as u64;
        manifest.counts.versions = archive.runtime.versions.len() as u64;
        manifest.counts.working_copies = archive.runtime.working_copies.len() as u64;
        manifest.counts.materials = archive.inventory.materials.len() as u64;
        manifest.counts.adjustments = archive.inventory.adjustments.len() as u64;

        Self::new(archive.exported_at.clone(), manifest, entries)
    }

    pub fn validate(&self) -> Result<(), ArchiveCodecError> {
        if self.exported_at.trim().is_empty() {
            return Err(ArchiveCodecError::Invalid(
                "archive.exportedAt must not be empty".into(),
            ));
        }
        self.manifest.validate()?;
        validate_manifest_layout(&self.manifest)?;

        if self.entries.contains_key(ARCHIVE_METADATA_PATH) {
            return Err(ArchiveCodecError::ForbiddenControlEntry(
                ARCHIVE_METADATA_PATH.into(),
            ));
        }
        if self.entries.contains_key(MANIFEST_PATH) {
            return Err(ArchiveCodecError::ForbiddenControlEntry(
                MANIFEST_PATH.into(),
            ));
        }

        let mut counts = EntryCounts::default();
        for path in self.entries.keys() {
            counts.increment(classify_data_entry(path)?);
        }
        if !self.entries.contains_key(&self.manifest.files.settings) {
            return Err(ArchiveCodecError::MissingRequiredEntry(
                self.manifest.files.settings.clone(),
            ));
        }
        counts.matches_manifest(&self.manifest)
    }

    /// Writes a stable ZIP byte stream with lexicographically sorted JSON entry names.
    pub fn encode_zip(&self) -> Result<Vec<u8>, ArchiveCodecError> {
        self.validate()?;

        let mut serialized = BTreeMap::new();
        serialized.insert(
            ARCHIVE_METADATA_PATH.to_owned(),
            canonical_json_bytes(&ArchiveMetadata {
                schema: DIRECTORY_TREE_ARCHIVE_SCHEMA.into(),
                exported_at: self.exported_at.clone(),
            })?,
        );
        serialized.insert(
            MANIFEST_PATH.to_owned(),
            canonical_json_bytes(&self.manifest)?,
        );
        for (path, value) in &self.entries {
            serialized.insert(path.clone(), canonical_json_bytes(value)?);
        }

        let cursor = Cursor::new(Vec::new());
        let mut writer = ZipWriter::new(cursor);
        for (path, bytes) in serialized {
            let options = SimpleFileOptions::default()
                .compression_method(CompressionMethod::Deflated)
                .unix_permissions(0o644);
            writer.start_file(path, options)?;
            writer.write_all(&bytes)?;
        }
        Ok(writer.finish()?.into_inner())
    }

    /// Decodes a directory-tree archive. Legacy single-snapshot ZIPs return a targeted error;
    /// callers that need them can use [`decode_archive_zip`] or
    /// [`decode_legacy_archive_metadata`].
    pub fn decode_zip(bytes: &[u8]) -> Result<Self, ArchiveCodecError> {
        match decode_archive_zip(bytes)? {
            ArchiveZipInput::DirectoryTree(archive) => Ok(archive),
            ArchiveZipInput::LegacySnapshot(_) => {
                Err(ArchiveCodecError::LegacySnapshotRequiresDirectDecode)
            }
        }
    }

    pub fn to_devd_data_archive(&self) -> Result<DevdDataArchive, ArchiveCodecError> {
        self.validate()?;
        let mut runtime = RuntimeSnapshot {
            schema: tuckmark_contracts::RUNTIME_EXPORT_SCHEMA.into(),
            exported_at: self.exported_at.clone(),
            snapshot_updated_at: self.manifest.snapshot_updated_at.clone(),
            settings: self.entries[&self.manifest.files.settings].clone(),
            templates: Vec::new(),
            versions: Vec::new(),
            working_copies: Vec::new(),
            extra: Default::default(),
        };
        let mut inventory = InventorySnapshot::default();

        for (path, value) in &self.entries {
            match classify_data_entry(path)? {
                EntryKind::Settings => {}
                EntryKind::Template => runtime
                    .templates
                    .push(serde_json::from_value::<TemplateRecord>(value.clone())?),
                EntryKind::Version => runtime
                    .versions
                    .push(serde_json::from_value::<TemplateVersion>(value.clone())?),
                EntryKind::WorkingCopy => {
                    runtime
                        .working_copies
                        .push(serde_json::from_value::<WorkingCopyRecord>(value.clone())?)
                }
                EntryKind::Material => inventory
                    .materials
                    .push(serde_json::from_value::<InventoryMaterial>(value.clone())?),
                EntryKind::Adjustment => inventory.adjustments.push(serde_json::from_value::<
                    InventoryAdjustment,
                >(
                    value.clone()
                )?),
            }
        }
        runtime
            .templates
            .sort_by(|left, right| left.id.cmp(&right.id));
        runtime
            .versions
            .sort_by(|left, right| left.id.cmp(&right.id));
        runtime
            .working_copies
            .sort_by(|left, right| left.source_key.cmp(&right.source_key));
        inventory
            .materials
            .sort_by(|left, right| left.id.cmp(&right.id));
        inventory
            .adjustments
            .sort_by(|left, right| left.id.cmp(&right.id));

        let archive = DevdDataArchive {
            schema: tuckmark_contracts::DEVD_DATA_ARCHIVE_SCHEMA.into(),
            exported_at: self.exported_at.clone(),
            runtime,
            inventory,
            extra: Default::default(),
        };
        archive.validate()?;
        Ok(archive)
    }
}

/// Decodes either currently supported directory-tree ZIPs or a legacy single-snapshot ZIP.
pub fn decode_archive_zip(bytes: &[u8]) -> Result<ArchiveZipInput, ArchiveCodecError> {
    let mut entries = read_zip_json_entries(bytes)?;
    let metadata = entries
        .remove(ARCHIVE_METADATA_PATH)
        .ok_or_else(|| ArchiveCodecError::MissingRequiredEntry(ARCHIVE_METADATA_PATH.into()))?;
    let schema = metadata
        .get("schema")
        .and_then(Value::as_str)
        .ok_or_else(|| ArchiveCodecError::Invalid("archive metadata schema is missing".into()))?;

    if schema == LEGACY_DATA_ARCHIVE_SCHEMA {
        return Ok(ArchiveZipInput::LegacySnapshot(
            decode_legacy_archive_metadata(&metadata)?,
        ));
    }
    if schema != DIRECTORY_TREE_ARCHIVE_SCHEMA {
        return Err(ArchiveCodecError::UnsupportedMetadataSchema(schema.into()));
    }

    let metadata: ArchiveMetadata = serde_json::from_value(metadata)?;
    if metadata.exported_at.trim().is_empty() {
        return Err(ArchiveCodecError::Invalid(
            "archive.exportedAt must not be empty".into(),
        ));
    }
    let manifest = entries
        .remove(MANIFEST_PATH)
        .ok_or_else(|| ArchiveCodecError::MissingRequiredEntry(MANIFEST_PATH.into()))?;
    let manifest = serde_json::from_value(manifest)?;

    Ok(ArchiveZipInput::DirectoryTree(DirectoryTreeArchive::new(
        metadata.exported_at,
        manifest,
        entries,
    )?))
}

/// Decodes the JSON object stored in `archive.json` for the legacy snapshot format.
pub fn decode_legacy_archive_metadata(
    metadata: &Value,
) -> Result<DevdDataArchive, ArchiveCodecError> {
    let schema = metadata
        .get("schema")
        .and_then(Value::as_str)
        .ok_or_else(|| ArchiveCodecError::Invalid("archive metadata schema is missing".into()))?;
    if schema != LEGACY_DATA_ARCHIVE_SCHEMA {
        return Err(ArchiveCodecError::UnsupportedMetadataSchema(schema.into()));
    }
    let normalized = normalize_legacy_value(metadata.clone())?;
    let archive = serde_json::from_value::<DevdDataArchive>(normalized)?;
    archive.validate()?;
    Ok(archive)
}

#[derive(Default)]
struct EntryCounts {
    templates: u64,
    versions: u64,
    working_copies: u64,
    materials: u64,
    adjustments: u64,
}

impl EntryCounts {
    fn increment(&mut self, kind: EntryKind) {
        match kind {
            EntryKind::Settings => {}
            EntryKind::Template => self.templates += 1,
            EntryKind::Version => self.versions += 1,
            EntryKind::WorkingCopy => self.working_copies += 1,
            EntryKind::Material => self.materials += 1,
            EntryKind::Adjustment => self.adjustments += 1,
        }
    }

    fn matches_manifest(&self, manifest: &DataDirectoryManifest) -> Result<(), ArchiveCodecError> {
        for (kind, expected, actual) in [
            ("templates", manifest.counts.templates, self.templates),
            ("versions", manifest.counts.versions, self.versions),
            (
                "workingCopies",
                manifest.counts.working_copies,
                self.working_copies,
            ),
            ("materials", manifest.counts.materials, self.materials),
            ("adjustments", manifest.counts.adjustments, self.adjustments),
        ] {
            if expected != actual {
                return Err(ArchiveCodecError::ManifestCountMismatch {
                    kind,
                    expected,
                    actual,
                });
            }
        }
        Ok(())
    }
}

fn validate_manifest_layout(manifest: &DataDirectoryManifest) -> Result<(), ArchiveCodecError> {
    for (name, actual, expected) in [
        (
            "manifest.files.settings",
            &manifest.files.settings,
            SETTINGS_PATH,
        ),
        (
            "manifest.files.templatesDir",
            &manifest.files.templates_dir,
            "templates",
        ),
        (
            "manifest.files.draftsDir",
            &manifest.files.drafts_dir,
            "drafts",
        ),
        (
            "manifest.files.inventoryDir",
            &manifest.files.inventory_dir,
            "inventory",
        ),
        (
            "manifest.files.backupsDir",
            &manifest.files.backups_dir,
            "backups",
        ),
    ] {
        if actual != expected {
            return Err(ArchiveCodecError::Invalid(format!(
                "{name} must be {expected}, received {actual}"
            )));
        }
    }
    Ok(())
}

fn read_zip_json_entries(bytes: &[u8]) -> Result<BTreeMap<String, Value>, ArchiveCodecError> {
    let central_paths = read_central_directory_paths(bytes)?;
    let mut archive = ZipArchive::new(Cursor::new(bytes))?;
    if archive.len() != central_paths.len() {
        return Err(ArchiveCodecError::Invalid(
            "ZIP archive entry count does not match its central directory".into(),
        ));
    }
    if archive.len() > MAX_ENTRY_COUNT {
        return Err(ArchiveCodecError::TooManyEntries(archive.len()));
    }

    let mut total_size = 0_u64;
    let mut seen = BTreeSet::new();
    let mut entries = BTreeMap::new();
    for (index, expected_path) in central_paths.iter().enumerate() {
        let mut entry = archive.by_index(index)?;
        let path = entry.name().to_owned();
        if path != *expected_path {
            return Err(ArchiveCodecError::Invalid(format!(
                "ZIP entry name differs from central directory at index {index}"
            )));
        }
        if entry.is_dir() || path.ends_with('/') {
            return Err(ArchiveCodecError::DirectoryEntry(path));
        }
        validate_zip_entry_path(&path)?;
        if !seen.insert(path.clone()) {
            return Err(ArchiveCodecError::DuplicateEntry(path));
        }
        if entry.size() > MAX_ENTRY_BYTES {
            return Err(ArchiveCodecError::EntryTooLarge {
                path,
                size: entry.size(),
            });
        }
        total_size = total_size
            .checked_add(entry.size())
            .ok_or(ArchiveCodecError::TotalTooLarge(u64::MAX))?;
        if total_size > MAX_TOTAL_BYTES {
            return Err(ArchiveCodecError::TotalTooLarge(total_size));
        }

        let mut payload = Vec::new();
        entry.read_to_end(&mut payload)?;
        let value = serde_json::from_slice(&payload)?;
        entries.insert(path, value);
    }
    Ok(entries)
}

fn read_central_directory_paths(bytes: &[u8]) -> Result<Vec<String>, ArchiveCodecError> {
    let end = find_end_of_central_directory(bytes).ok_or_else(|| {
        ArchiveCodecError::Invalid("ZIP end of central directory is missing or malformed".into())
    })?;
    let disk = read_u16(bytes, end + 4)?;
    let central_disk = read_u16(bytes, end + 6)?;
    let entries_on_disk = read_u16(bytes, end + 8)?;
    let entry_count = read_u16(bytes, end + 10)?;
    let central_size = u64::from(read_u32(bytes, end + 12)?);
    let central_offset = u64::from(read_u32(bytes, end + 16)?);
    if disk != 0 || central_disk != 0 || entries_on_disk != entry_count {
        return Err(ArchiveCodecError::Invalid(
            "multi-disk ZIP archives are not supported".into(),
        ));
    }
    if entry_count == u16::MAX || central_size == u64::from(u32::MAX) {
        return Err(ArchiveCodecError::Invalid(
            "ZIP64 central directories are not supported".into(),
        ));
    }
    if usize::from(entry_count) > MAX_ENTRY_COUNT {
        return Err(ArchiveCodecError::TooManyEntries(usize::from(entry_count)));
    }

    let start = usize::try_from(central_offset).map_err(|_| {
        ArchiveCodecError::Invalid("ZIP central directory offset is out of range".into())
    })?;
    let size = usize::try_from(central_size).map_err(|_| {
        ArchiveCodecError::Invalid("ZIP central directory size is out of range".into())
    })?;
    let central_end = start.checked_add(size).ok_or_else(|| {
        ArchiveCodecError::Invalid("ZIP central directory range overflows".into())
    })?;
    if central_end > end || central_end > bytes.len() {
        return Err(ArchiveCodecError::Invalid(
            "ZIP central directory is outside the archive".into(),
        ));
    }

    let mut paths = Vec::with_capacity(usize::from(entry_count));
    let mut seen = BTreeSet::new();
    let mut offset = start;
    for _ in 0..entry_count {
        if read_u32(bytes, offset)? != 0x0201_4b50 {
            return Err(ArchiveCodecError::Invalid(
                "ZIP central directory entry signature is invalid".into(),
            ));
        }
        let name_length = usize::from(read_u16(bytes, offset + 28)?);
        let extra_length = usize::from(read_u16(bytes, offset + 30)?);
        let comment_length = usize::from(read_u16(bytes, offset + 32)?);
        let header_end = offset.checked_add(46).ok_or_else(|| {
            ArchiveCodecError::Invalid("ZIP central directory entry range overflows".into())
        })?;
        let name_end = header_end.checked_add(name_length).ok_or_else(|| {
            ArchiveCodecError::Invalid("ZIP central directory entry name range overflows".into())
        })?;
        let record_end = name_end
            .checked_add(extra_length)
            .and_then(|value| value.checked_add(comment_length))
            .ok_or_else(|| {
                ArchiveCodecError::Invalid(
                    "ZIP central directory entry metadata range overflows".into(),
                )
            })?;
        if record_end > central_end {
            return Err(ArchiveCodecError::Invalid(
                "ZIP central directory entry exceeds its declared range".into(),
            ));
        }
        let path = std::str::from_utf8(&bytes[header_end..name_end])
            .map_err(|_| ArchiveCodecError::Invalid("ZIP entry name is not UTF-8".into()))?
            .to_owned();
        validate_zip_entry_path(&path)?;
        if !seen.insert(path.clone()) {
            return Err(ArchiveCodecError::DuplicateEntry(path));
        }
        paths.push(path);
        offset = record_end;
    }
    if offset != central_end {
        return Err(ArchiveCodecError::Invalid(
            "ZIP central directory has trailing bytes".into(),
        ));
    }
    Ok(paths)
}

fn find_end_of_central_directory(bytes: &[u8]) -> Option<usize> {
    const END_HEADER_SIZE: usize = 22;
    const MAX_COMMENT_SIZE: usize = u16::MAX as usize;
    if bytes.len() < END_HEADER_SIZE {
        return None;
    }
    let search_start = bytes
        .len()
        .saturating_sub(END_HEADER_SIZE.saturating_add(MAX_COMMENT_SIZE));
    for offset in (search_start..=bytes.len() - END_HEADER_SIZE).rev() {
        if bytes.get(offset..offset + 4) != Some(b"PK\x05\x06") {
            continue;
        }
        let comment_length = usize::from(u16::from_le_bytes([
            *bytes.get(offset + 20)?,
            *bytes.get(offset + 21)?,
        ]));
        if offset + END_HEADER_SIZE + comment_length == bytes.len() {
            return Some(offset);
        }
    }
    None
}

fn read_u16(bytes: &[u8], offset: usize) -> Result<u16, ArchiveCodecError> {
    let value = bytes
        .get(offset..offset + 2)
        .ok_or_else(|| ArchiveCodecError::Invalid("ZIP structure ends unexpectedly".into()))?;
    Ok(u16::from_le_bytes([value[0], value[1]]))
}

fn read_u32(bytes: &[u8], offset: usize) -> Result<u32, ArchiveCodecError> {
    let value = bytes
        .get(offset..offset + 4)
        .ok_or_else(|| ArchiveCodecError::Invalid("ZIP structure ends unexpectedly".into()))?;
    Ok(u32::from_le_bytes([value[0], value[1], value[2], value[3]]))
}

fn validate_zip_entry_path(path: &str) -> Result<(), ArchiveCodecError> {
    if path == ARCHIVE_METADATA_PATH || path == MANIFEST_PATH {
        return Ok(());
    }
    classify_data_entry(path).map(|_| ())
}

fn classify_data_entry(path: &str) -> Result<EntryKind, ArchiveCodecError> {
    validate_safe_relative_path(path)?;
    if !path.ends_with(".json") {
        return Err(ArchiveCodecError::NonJsonEntry(path.into()));
    }
    let parts: Vec<_> = path.split('/').collect();
    match parts.as_slice() {
        ["settings", "app-settings.json"] => Ok(EntryKind::Settings),
        ["templates", _, "template.json"] => Ok(EntryKind::Template),
        ["templates", _, "working-copy.json"] => Ok(EntryKind::WorkingCopy),
        ["templates", _, "versions", file] if valid_json_filename(file) => Ok(EntryKind::Version),
        ["drafts", _, file] if valid_json_filename(file) => Ok(EntryKind::WorkingCopy),
        ["inventory", "materials", file] if valid_json_filename(file) => Ok(EntryKind::Material),
        ["inventory", "adjustments", file] if valid_json_filename(file) => {
            Ok(EntryKind::Adjustment)
        }
        _ => Err(ArchiveCodecError::Invalid(format!(
            "unsupported archive data entry {path}"
        ))),
    }
}

fn validate_safe_relative_path(path: &str) -> Result<(), ArchiveCodecError> {
    if path.is_empty()
        || path.starts_with('/')
        || path.contains('\\')
        || path.chars().any(char::is_control)
    {
        return Err(ArchiveCodecError::UnsafeEntryPath(path.into()));
    }
    let mut parts = path.split('/');
    let first = parts
        .next()
        .ok_or_else(|| ArchiveCodecError::UnsafeEntryPath(path.into()))?;
    if first == ".tuckmark" || first == "backups" {
        return Err(ArchiveCodecError::ForbiddenControlEntry(path.into()));
    }
    if first.is_empty() || first == "." || first == ".." {
        return Err(ArchiveCodecError::UnsafeEntryPath(path.into()));
    }
    for part in parts {
        if part.is_empty() || part == "." || part == ".." {
            return Err(ArchiveCodecError::UnsafeEntryPath(path.into()));
        }
    }
    Ok(())
}

fn valid_json_filename(name: &str) -> bool {
    name.strip_suffix(".json")
        .is_some_and(|stem| !stem.is_empty())
}

fn insert_entry(
    entries: &mut BTreeMap<String, Value>,
    path: String,
    value: Value,
) -> Result<(), ArchiveCodecError> {
    classify_data_entry(&path)?;
    if entries.insert(path.clone(), value).is_some() {
        return Err(ArchiveCodecError::DuplicateEntry(path));
    }
    Ok(())
}

fn safe_segment(value: &str) -> Result<&str, ArchiveCodecError> {
    if value.is_empty()
        || value == "."
        || value == ".."
        || value.contains('/')
        || value.contains('\\')
        || value.chars().any(char::is_control)
    {
        return Err(ArchiveCodecError::UnsafeEntryPath(value.into()));
    }
    Ok(value)
}

fn working_copy_path(copy: &WorkingCopyRecord) -> Result<String, ArchiveCodecError> {
    if let Some(template_id) = copy.source_key.strip_prefix("user:") {
        return Ok(format!(
            "templates/{}/working-copy.json",
            safe_segment(template_id)?
        ));
    }

    let source = copy.source.as_ref().and_then(Value::as_object);
    let kind = source
        .and_then(|source| source.get("kind"))
        .and_then(Value::as_str)
        .unwrap_or("scratch");
    let identifier = source
        .and_then(|source| source.get("presetId"))
        .or_else(|| source.and_then(|source| source.get("id")))
        .and_then(Value::as_str)
        .or_else(|| copy.source_key.split_once(':').map(|(_, value)| value))
        .unwrap_or(&copy.source_key);
    Ok(format!(
        "drafts/{}/{}.json",
        safe_segment(kind)?,
        safe_segment(identifier)?,
    ))
}
