import { DEFAULT_TEXT_FONT_FAMILY, getTextFontDefinition, resolveTextFontFamily, TEXT_FONT_FAMILY_STACKS, type TextFontDefinition, type TextFontFamily, type TextFontPickerFamily, textFontFamilies, textFontPickerFamilies, textFontRegistry } from "./text-font-registry.js";
export { DEFAULT_TEXT_FONT_FAMILY, getTextFontDefinition, resolveTextFontFamily, TEXT_FONT_FAMILY_STACKS, type TextFontDefinition, type TextFontFamily, type TextFontPickerFamily, textFontFamilies, textFontPickerFamilies, textFontRegistry, };
export declare const TEXT_LINE_HEIGHT_RATIO = 1.2;
export declare const DEFAULT_TEXT_LINE_HEIGHT = 1.2;
export declare const TEXT_VISUAL_TOP_TRIM_RATIO = 0.18;
export declare const TEXT_VISUAL_ASCENT_RATIO: number;
export declare const TEXT_VISUAL_DESCENT_RATIO: number;
export declare const textVerticalAlignments: readonly ["top", "middle", "bottom"];
export type TextVerticalAlign = (typeof textVerticalAlignments)[number];
export declare const textHorizontalAlignments: readonly ["left", "center", "right", "justify"];
export type TextHorizontalAlign = (typeof textHorizontalAlignments)[number];
export declare const DEFAULT_TEXT_VERTICAL_ALIGN: TextVerticalAlign;
export type TextLayoutInput = {
    text: string;
    fontSize: number;
    fontFamily?: TextFontFamily | undefined;
    fontWeight?: "normal" | "bold" | undefined;
    width: number;
    height: number;
    lineHeight?: number | undefined;
    align?: TextHorizontalAlign | undefined;
    maxLines?: number | undefined;
    verticalAlign?: TextVerticalAlign | undefined;
    stretchX?: boolean | undefined;
    stretchY?: boolean | undefined;
    autoWrap?: boolean | undefined;
    verticalText?: boolean | undefined;
    measureText?: TextMeasureFunction | undefined;
};
export type TextMeasureInput = {
    text: string;
    fontSize: number;
    fontFamily?: TextFontFamily | undefined;
    fontWeight?: "normal" | "bold" | undefined;
};
export type TextMeasurement = {
    width: number;
    actualBoundingBoxAscent?: number | undefined;
    actualBoundingBoxDescent?: number | undefined;
    actualBoundingBoxLeft?: number | undefined;
    actualBoundingBoxRight?: number | undefined;
    fontBoundingBoxAscent?: number | undefined;
    fontBoundingBoxDescent?: number | undefined;
};
export type TextMeasureFunction = (input: TextMeasureInput) => TextMeasurement | undefined;
export type TextLayoutLine = {
    text: string;
    x: number;
    y: number;
    width: number;
    letterSpacing: number;
};
export type TextLayoutGlyph = {
    text: string;
    x: number;
    y: number;
};
export type TextLayout = {
    lines: string[];
    lineLayouts: TextLayoutLine[];
    glyphs: TextLayoutGlyph[];
    verticalText: boolean;
    lineHeight: number;
    renderHeight: number;
    naturalWidth: number;
    naturalHeight: number;
    contentX: number;
    contentY: number;
    contentWidth: number;
    contentHeight: number;
    textOffsetX: number;
    textOffsetY: number;
    baselineOffsetY: number;
    scaleX: number;
    scaleY: number;
};
export declare function wrapText(text: string, maxCharsPerLine: number, maxLines?: number): string[];
export declare function wrapTextByWidth(text: string, fontSize: number, width?: number, maxLines?: number, autoWrap?: boolean, fontFamily?: TextFontFamily, measureText?: TextMeasureFunction, fontWeight?: "normal" | "bold"): string[];
export declare function estimateCharsPerLine(fontSize: number, width?: number, fontFamily?: TextFontFamily): number;
export declare function estimateTextLineWidth(line: string, fontSize: number, fontFamily?: TextFontFamily): number;
export declare function normalizeTextLineHeight(lineHeight?: number): number;
export declare function getTextNaturalHeight(fontSize: number, lineCount: number, lineHeight?: number): number;
export declare function getTextFontFamilyStack(fontFamily?: TextFontFamily): string;
export declare function resolveTextLayout(input: TextLayoutInput): TextLayout;
