export declare const TEXT_LINE_HEIGHT_RATIO = 1.2;
export declare const DEFAULT_TEXT_LINE_HEIGHT = 1.2;
export declare const TEXT_VISUAL_TOP_TRIM_RATIO = 0.18;
export declare const TEXT_VISUAL_ASCENT_RATIO: number;
export declare const TEXT_VISUAL_DESCENT_RATIO: number;
export declare const TEXT_AVERAGE_GLYPH_WIDTH_RATIO = 0.78;
export declare const textVerticalAlignments: readonly ["top", "middle", "bottom"];
export type TextVerticalAlign = (typeof textVerticalAlignments)[number];
export declare const textHorizontalAlignments: readonly ["left", "center", "right", "justify"];
export type TextHorizontalAlign = (typeof textHorizontalAlignments)[number];
export declare const textFontFamilies: readonly ["system-sans", "system-serif", "system-mono", "arial", "noto-sans-sc"];
export type TextFontFamily = (typeof textFontFamilies)[number];
export declare const DEFAULT_TEXT_FONT_FAMILY: TextFontFamily;
export declare const DEFAULT_TEXT_VERTICAL_ALIGN: TextVerticalAlign;
export declare const TEXT_FONT_FAMILY_STACKS: Record<TextFontFamily, string>;
export type TextLayoutInput = {
    text: string;
    fontSize: number;
    width: number;
    height: number;
    lineHeight?: number | undefined;
    align?: TextHorizontalAlign | undefined;
    maxLines?: number | undefined;
    verticalAlign?: TextVerticalAlign | undefined;
    stretchX?: boolean | undefined;
    stretchY?: boolean | undefined;
    autoWrap?: boolean | undefined;
    verticalText?: boolean | undefined;
};
export type TextLayoutLine = {
    text: string;
    x: number;
    y: number;
    width: number;
    letterSpacing: number;
};
export type TextLayoutGlyph = {
    text: string;
    x: number;
    y: number;
};
export type TextLayout = {
    lines: string[];
    lineLayouts: TextLayoutLine[];
    glyphs: TextLayoutGlyph[];
    verticalText: boolean;
    lineHeight: number;
    renderHeight: number;
    naturalWidth: number;
    naturalHeight: number;
    contentX: number;
    contentY: number;
    contentWidth: number;
    contentHeight: number;
    textOffsetY: number;
    baselineOffsetY: number;
    scaleX: number;
    scaleY: number;
};
export declare function wrapText(text: string, maxCharsPerLine: number, maxLines?: number): string[];
export declare function wrapTextByWidth(text: string, fontSize: number, width?: number, maxLines?: number, autoWrap?: boolean): string[];
export declare function estimateCharsPerLine(fontSize: number, width?: number): number;
export declare function estimateTextLineWidth(line: string, fontSize: number): number;
export declare function normalizeTextLineHeight(lineHeight?: number): number;
export declare function getTextNaturalHeight(fontSize: number, lineCount: number, lineHeight?: number): number;
export declare function getTextFontFamilyStack(fontFamily?: TextFontFamily): string;
export declare function resolveTextLayout(input: TextLayoutInput): TextLayout;
