[package]
name = "tuckmark-cli"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "tuckmark"
path = "src/main.rs"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.32", features = ["derive"] }
libc = "0.2.172"
serde.workspace = true
serde_json.workspace = true
sha2 = "0.10.8"
thiserror.workspace = true
time = { version = "0.3.37", features = ["formatting"] }
tuckmark-contracts = { path = "../tuckmark-contracts" }
tuckmark-engine = { path = "../tuckmark-engine" }
uuid.workspace = true

[dev-dependencies]
tempfile = "3.16.0"
